version: '3.1'
services:
  stats-server:
    build: ./stats/server
    image: stat-server
    container_name: stat-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - SPRING_DATASOURCE_USER=bogdan
      - SPRING_DATASOURCE_PASSWORD=bogdan
      - DB_NAME=stats
      - DB_HOST=stats-db
        DB_PORT=5432

  stats-db:
    image: postgres:14-alpine
    container_name: statsDb
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=bogdan
      - POSTGRES_PASSWORD=bogdan

  ewm-service:
    build: ./main
    image: main-service
    container_name: main-service
    ports:
      - "8080:8080"
    depends_on:
      - stats-server
      - ewm-db
    environment:
      - application.name=explore-main
      - stat-server.url=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm
      - SPRING_DATASOURCE_USER=bogdan
      - SPRING_DATASOURCE_PASSWORD=bogdan
      - DB_NAME=ewm
      - DB_HOST=db
        DB_PORT=5432

  ewm-db:
    image: postgres:14-alpine
    container_name: ewmDb
    ports:
      - "6540:5432"
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=bogdan
      - POSTGRES_PASSWORD=bogdan